# fly.toml file generated for weathered-firefly-2748 on 2023-04-15T04:00:45+05:00

app = "weathered-firefly-2748"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
